language: ruby
rvm:
- 2.2.2

install:
- npm install gitbook-cli -g
- gitbook install
- gitbook build
- gem install html-proofer

script: 

- htmlproofer ./_book --empty-alt-ignore true --check-external-hash true


# branch whitelist
branches:
  only:
  - master      # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer
