language: ruby
rvm:
- 2.2.2

install:
- npm install gitbook-cli -g
- gitbook install
- gitbook build
- gem install html-proofer

script: 

- htmlproofer ./_book 
  --empty-alt-ignore true 
  --check-external-hash true
  --url-ignore 'https://img.shields.io/badge/discuss-px4-ff69b4.svg,https://img.shields.io/github/release/PX4/Firmware.svg'



env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer
