# TEST WORKFLOW TO DEPLOY

name: DEPLOYTEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events to the v1.test_vtol branch
  push:
    branches: [ v1.test_vtol ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the docs
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: Install dependencies -yarn
        run: yarn
        
      - name: Generate static vuepress files
        run: yarn docs:build

